package com.jkblog.mapper;

import com.jkblog.bean.BlogCategory;
import com.jkblog.bean.BlogCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

public interface BlogCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    long countByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int deleteByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int deleteByPrimaryKey(Integer categoryId);

    int categoryCountIncrement(Integer categoryId);
    int categoryCountDecrement(Integer categoryId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int insert(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int insertSelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    List<BlogCategory> selectByExample(BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    BlogCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") BlogCategory record, @Param("example") BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByExample(@Param("record") BlogCategory record, @Param("example") BlogCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByPrimaryKeySelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByPrimaryKey(BlogCategory record);


    @Update("update blogcategory set categoryCount=categoryCount-1 where categoryId=#{categoryId} and categoryCount>0")
    int decrementCategoryById(Integer categoryId);
}