package com.jkblog.mapper;

import com.jkblog.bean.BlogComment;
import com.jkblog.bean.BlogCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface BlogCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    long countByExample(BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    int deleteByExample(BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    int deleteByPrimaryKey(Integer blogCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    int insert(BlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    int insertSelective(BlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    List<BlogComment> selectByExample(BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    BlogComment selectByPrimaryKey(Integer blogCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") BlogComment record, @Param("example") BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    int updateByExample(@Param("record") BlogComment record, @Param("example") BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    int updateByPrimaryKeySelective(BlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbg.generated Fri Nov 06 17:28:09 CST 2020
     */
    int updateByPrimaryKey(BlogComment record);

    int updateSonCount(Integer blogSonId);

    @Select("")
    List<BlogComment> getCommentsByFather(Integer fatherId);
}