package com.jkblog.mapper;

import com.jkblog.bean.BlogLabel;
import com.jkblog.bean.BlogLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    long countByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int deleteByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int deleteByPrimaryKey(Integer labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int insert(BlogLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int insertSelective(BlogLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    List<BlogLabel> selectByExample(BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    BlogLabel selectByPrimaryKey(Integer labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") BlogLabel record, @Param("example") BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByExample(@Param("record") BlogLabel record, @Param("example") BlogLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByPrimaryKeySelective(BlogLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloglabel
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByPrimaryKey(BlogLabel record);
}