package com.jkblog.mapper;

import com.jkblog.bean.BlogUser;
import com.jkblog.bean.BlogUserExample;

import java.io.InputStream;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

public interface BlogUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    long countByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int deleteByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int insert(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int insertSelective(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    List<BlogUser> selectByExample(BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    BlogUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") BlogUser record, @Param("example") BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByExample(@Param("record") BlogUser record, @Param("example") BlogUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByPrimaryKeySelective(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloguser
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByPrimaryKey(BlogUser record);

    @Update("update bloguser set userBlogCount=userBlogCount-1 where userId=#{userId} and userBlogCount>0")
    int decrementUserBlogsCountById(Integer userId);

    @Update("update bloguser set userBlogCount=userBlogCount+1 where userId=#{userId}")
    int incrementUserBlogsCountById(Integer userId);
}