package com.jkblog.mapper;

import com.jkblog.bean.FollowFanMap;
import com.jkblog.bean.FollowFanMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowFanMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    long countByExample(FollowFanMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int deleteByExample(FollowFanMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int deleteByPrimaryKey(Integer followFanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int insert(FollowFanMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int insertSelective(FollowFanMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    List<FollowFanMap> selectByExample(FollowFanMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    FollowFanMap selectByPrimaryKey(Integer followFanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") FollowFanMap record, @Param("example") FollowFanMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByExample(@Param("record") FollowFanMap record, @Param("example") FollowFanMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByPrimaryKeySelective(FollowFanMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followfanmap
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    int updateByPrimaryKey(FollowFanMap record);
}