package com.jkblog.bean;

public class BlogCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcategory.categoryId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcategory.categoryName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcategory.categoryDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String categoryDescription;

    private Integer categoryCount;

    public Integer getCategoryCount() {
        return categoryCount;
    }

    public void setCategoryCount(Integer categoryCount) {
        this.categoryCount = categoryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcategory.categoryId
     *
     * @return the value of blogcategory.categoryId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcategory.categoryId
     *
     * @param categoryId the value for blogcategory.categoryId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcategory.categoryName
     *
     * @return the value of blogcategory.categoryName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcategory.categoryName
     *
     * @param categoryName the value for blogcategory.categoryName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcategory.categoryDescription
     *
     * @return the value of blogcategory.categoryDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getCategoryDescription() {
        return categoryDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcategory.categoryDescription
     *
     * @param categoryDescription the value for blogcategory.categoryDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription == null ? null : categoryDescription.trim();
    }
}