package com.jkblog.bean;

import java.util.Date;

public class BlogComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private Integer blogCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentContents
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private String blogCommentContents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentTime
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private Date blogCommentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentUserId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private Integer blogCommentUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentBlogId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private Integer blogCommentBlogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentBlogSonId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private Integer blogCommentBlogSonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentFather
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private Integer blogCommentFather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentUserName
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private String blogCommentUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogCommentSonCount
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    private Integer blogCommentSonCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentId
     *
     * @return the value of blogcomment.blogCommentId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public Integer getBlogCommentId() {
        return blogCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentId
     *
     * @param blogCommentId the value for blogcomment.blogCommentId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentId(Integer blogCommentId) {
        this.blogCommentId = blogCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentContents
     *
     * @return the value of blogcomment.blogCommentContents
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public String getBlogCommentContents() {
        return blogCommentContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentContents
     *
     * @param blogCommentContents the value for blogcomment.blogCommentContents
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentContents(String blogCommentContents) {
        this.blogCommentContents = blogCommentContents == null ? null : blogCommentContents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentTime
     *
     * @return the value of blogcomment.blogCommentTime
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public Date getBlogCommentTime() {
        return blogCommentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentTime
     *
     * @param blogCommentTime the value for blogcomment.blogCommentTime
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentTime(Date blogCommentTime) {
        this.blogCommentTime = blogCommentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentUserId
     *
     * @return the value of blogcomment.blogCommentUserId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public Integer getBlogCommentUserId() {
        return blogCommentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentUserId
     *
     * @param blogCommentUserId the value for blogcomment.blogCommentUserId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentUserId(Integer blogCommentUserId) {
        this.blogCommentUserId = blogCommentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentBlogId
     *
     * @return the value of blogcomment.blogCommentBlogId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public Integer getBlogCommentBlogId() {
        return blogCommentBlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentBlogId
     *
     * @param blogCommentBlogId the value for blogcomment.blogCommentBlogId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentBlogId(Integer blogCommentBlogId) {
        this.blogCommentBlogId = blogCommentBlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentBlogSonId
     *
     * @return the value of blogcomment.blogCommentBlogSonId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public Integer getBlogCommentBlogSonId() {
        return blogCommentBlogSonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentBlogSonId
     *
     * @param blogCommentBlogSonId the value for blogcomment.blogCommentBlogSonId
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentBlogSonId(Integer blogCommentBlogSonId) {
        this.blogCommentBlogSonId = blogCommentBlogSonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentFather
     *
     * @return the value of blogcomment.blogCommentFather
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public Integer getBlogCommentFather() {
        return blogCommentFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentFather
     *
     * @param blogCommentFather the value for blogcomment.blogCommentFather
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentFather(Integer blogCommentFather) {
        this.blogCommentFather = blogCommentFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentUserName
     *
     * @return the value of blogcomment.blogCommentUserName
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public String getBlogCommentUserName() {
        return blogCommentUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentUserName
     *
     * @param blogCommentUserName the value for blogcomment.blogCommentUserName
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentUserName(String blogCommentUserName) {
        this.blogCommentUserName = blogCommentUserName == null ? null : blogCommentUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogCommentSonCount
     *
     * @return the value of blogcomment.blogCommentSonCount
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public Integer getBlogCommentSonCount() {
        return blogCommentSonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogCommentSonCount
     *
     * @param blogCommentSonCount the value for blogcomment.blogCommentSonCount
     *
     * @mbg.generated Thu Nov 05 17:39:29 CST 2020
     */
    public void setBlogCommentSonCount(Integer blogCommentSonCount) {
        this.blogCommentSonCount = blogCommentSonCount;
    }
}