package com.jkblog.bean;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogTitle
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String blogTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogReadTimes
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer blogReadTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogCommentTimes
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer blogCommentTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogEditTime
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Date blogEditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer blogUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogCategoryId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer blogCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogBriefContent
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String blogBriefContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogContent
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogId
     *
     * @return the value of blog.blogId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogId
     *
     * @param blogId the value for blog.blogId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogTitle
     *
     * @return the value of blog.blogTitle
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogTitle
     *
     * @param blogTitle the value for blog.blogTitle
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogReadTimes
     *
     * @return the value of blog.blogReadTimes
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getBlogReadTimes() {
        return blogReadTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogReadTimes
     *
     * @param blogReadTimes the value for blog.blogReadTimes
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogReadTimes(Integer blogReadTimes) {
        this.blogReadTimes = blogReadTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogCommentTimes
     *
     * @return the value of blog.blogCommentTimes
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getBlogCommentTimes() {
        return blogCommentTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogCommentTimes
     *
     * @param blogCommentTimes the value for blog.blogCommentTimes
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogCommentTimes(Integer blogCommentTimes) {
        this.blogCommentTimes = blogCommentTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogEditTime
     *
     * @return the value of blog.blogEditTime
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Date getBlogEditTime() {
        return blogEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogEditTime
     *
     * @param blogEditTime the value for blog.blogEditTime
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogEditTime(Date blogEditTime) {
        this.blogEditTime = blogEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogUserId
     *
     * @return the value of blog.blogUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getBlogUserId() {
        return blogUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogUserId
     *
     * @param blogUserId the value for blog.blogUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogUserId(Integer blogUserId) {
        this.blogUserId = blogUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogCategoryId
     *
     * @return the value of blog.blogCategoryId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getBlogCategoryId() {
        return blogCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogCategoryId
     *
     * @param blogCategoryId the value for blog.blogCategoryId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogCategoryId(Integer blogCategoryId) {
        this.blogCategoryId = blogCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogBriefContent
     *
     * @return the value of blog.blogBriefContent
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getBlogBriefContent() {
        return blogBriefContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogBriefContent
     *
     * @param blogBriefContent the value for blog.blogBriefContent
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogBriefContent(String blogBriefContent) {
        this.blogBriefContent = blogBriefContent == null ? null : blogBriefContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogContent
     *
     * @return the value of blog.blogContent
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogContent
     *
     * @param blogContent the value for blog.blogContent
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }
}