package com.jkblog.bean;

public class BlogLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloglabel.labelId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloglabel.labelName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloglabel.labelDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String labelDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloglabel.labelId
     *
     * @return the value of bloglabel.labelId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloglabel.labelId
     *
     * @param labelId the value for bloglabel.labelId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloglabel.labelName
     *
     * @return the value of bloglabel.labelName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloglabel.labelName
     *
     * @param labelName the value for bloglabel.labelName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloglabel.labelDescription
     *
     * @return the value of bloglabel.labelDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getLabelDescription() {
        return labelDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloglabel.labelDescription
     *
     * @param labelDescription the value for bloglabel.labelDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setLabelDescription(String labelDescription) {
        this.labelDescription = labelDescription == null ? null : labelDescription.trim();
    }
}