package com.jkblog.bean;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.util.Date;

public class BlogUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    @Length(min = 2,max = 50,message = "{user.userName.not.length}")
    @Pattern( regexp = "[A-Za-z0-9\u4e00-\u9fa5]{2,50}",message = "{user.userName.not.pattern}")
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userPassword
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    @Pattern( regexp = "[A-Za-z0-9\u4e00-\u9fa5]{6,50}",message = "{user.userPassword.not.length}")
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String userDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userGender
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private String userGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userCreateTime
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Date userCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userBirthDay
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Date userBirthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userBlogCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer userBlogCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userEmail
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    @Email(message = "{user.useEmail.not.pattern}")
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userFollowCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer userFollowCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloguser.userFansCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer userFansCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userId
     *
     * @return the value of bloguser.userId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userId
     *
     * @param userId the value for bloguser.userId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userName
     *
     * @return the value of bloguser.userName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userName
     *
     * @param userName the value for bloguser.userName
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userPassword
     *
     * @return the value of bloguser.userPassword
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userPassword
     *
     * @param userPassword the value for bloguser.userPassword
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userDescription
     *
     * @return the value of bloguser.userDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getUserDescription() {
        return userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userDescription
     *
     * @param userDescription the value for bloguser.userDescription
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserDescription(String userDescription) {
        this.userDescription = userDescription == null ? null : userDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userGender
     *
     * @return the value of bloguser.userGender
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userGender
     *
     * @param userGender the value for bloguser.userGender
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userCreateTime
     *
     * @return the value of bloguser.userCreateTime
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userCreateTime
     *
     * @param userCreateTime the value for bloguser.userCreateTime
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userBirthDay
     *
     * @return the value of bloguser.userBirthDay
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Date getUserBirthDay() {
        return userBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userBirthDay
     *
     * @param userBirthDay the value for bloguser.userBirthDay
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserBirthDay(Date userBirthDay) {
        this.userBirthDay = userBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userBlogCount
     *
     * @return the value of bloguser.userBlogCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getUserBlogCount() {
        return userBlogCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userBlogCount
     *
     * @param userBlogCount the value for bloguser.userBlogCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserBlogCount(Integer userBlogCount) {
        this.userBlogCount = userBlogCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userEmail
     *
     * @return the value of bloguser.userEmail
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userEmail
     *
     * @param userEmail the value for bloguser.userEmail
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userFollowCount
     *
     * @return the value of bloguser.userFollowCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getUserFollowCount() {
        return userFollowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userFollowCount
     *
     * @param userFollowCount the value for bloguser.userFollowCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserFollowCount(Integer userFollowCount) {
        this.userFollowCount = userFollowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloguser.userFansCount
     *
     * @return the value of bloguser.userFansCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getUserFansCount() {
        return userFansCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloguser.userFansCount
     *
     * @param userFansCount the value for bloguser.userFansCount
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setUserFansCount(Integer userFansCount) {
        this.userFansCount = userFansCount;
    }
}