package com.jkblog.bean;

public class FollowFanMap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followfanmap.followFanId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer followFanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followfanmap.followUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer followUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followfanmap.fanUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    private Integer fanUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followfanmap.followFanId
     *
     * @return the value of followfanmap.followFanId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getFollowFanId() {
        return followFanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followfanmap.followFanId
     *
     * @param followFanId the value for followfanmap.followFanId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setFollowFanId(Integer followFanId) {
        this.followFanId = followFanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followfanmap.followUserId
     *
     * @return the value of followfanmap.followUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getFollowUserId() {
        return followUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followfanmap.followUserId
     *
     * @param followUserId the value for followfanmap.followUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setFollowUserId(Integer followUserId) {
        this.followUserId = followUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followfanmap.fanUserId
     *
     * @return the value of followfanmap.fanUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public Integer getFanUserId() {
        return fanUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followfanmap.fanUserId
     *
     * @param fanUserId the value for followfanmap.fanUserId
     *
     * @mbg.generated Mon Nov 02 23:27:58 CST 2020
     */
    public void setFanUserId(Integer fanUserId) {
        this.fanUserId = fanUserId;
    }
}